save_dir: "output_linear_1000/"
data_dir: "../data_linear_1000/"
d_model: 128
d_ff: 1024
dropout: 0.1
N_State: 6
N_Control: 6
attn_type: "softmax"
h: 8
nu: 1000
u_model: 128
batch_size: 256
lr: 0.001
num_epoches: 2500

